name: CI - NestJS API

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: test_club
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      NODE_ENV: test
      PORT: 3003

    steps:
      # -----------------------------
      # Checkout
      # -----------------------------
      - uses: actions/checkout@v4

      # -----------------------------
      # Node.js
      # -----------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # -----------------------------
      # Install deps
      # -----------------------------
      - run: npm install

      # -----------------------------
      # Prisma
      # -----------------------------
      - run: npx prisma generate

      # -----------------------------
      # Create .env.test
      # -----------------------------
      - name: Create .env.test
        run: |
          echo "NODE_ENV=test" > .env.test
          echo "DATABASE_URL=${{ secrets.DATABASE_URL_TEST }}" >> .env.test
          echo "JWT_SECRET=${{ secrets.JWT_SECRET_TEST }}" >> .env.test
          echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET_TEST }}" >> .env.test
          echo "JWT_RESET_SECRET=${{ secrets.JWT_RESET_SECRET_TEST }}" >> .env.test
          echo "JWT_VERIFY_SECRET=${{ secrets.JWT_VERIFY_SECRET_TEST }}" >> .env.test
          echo "MAIL_FROM=${{ secrets.MAIL_FROM_TEST }}" >> .env.test
          echo "GMAIL_USER=${{ secrets.GMAIL_USER_TEST }}" >> .env.test
          echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD_TEST }}" >> .env.test
          echo "FRONTEND_URL=https://mon-frontend-test.com" >> .env.test
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN_TEST }}" >> .env.test
          echo "SUPERADMIN_EMAIL=${{ secrets.SUPERADMIN_EMAIL_TEST }}" >> .env.test
          echo "SUPERADMIN_PASSWORD=${{ secrets.SUPERADMIN_PASSWORD_TEST }}" >> .env.test
          echo "THROTTLE_TTL=900" >> .env.test
          echo "THROTTLE_LIMIT=100" >> .env.test
          echo "PORT=3003" >> .env.test
          echo "CLOUDINARY_CLOUD_NAME=do3nd2woi" >> .env.test
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY_TEST }}" >> .env.test
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET_TEST }}" >> .env.test


      # -----------------------------
      # Reset + seed DB
      # -----------------------------
      - run: npm run test:reset
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}

      - run: npm run seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}

      # -----------------------------
      # Tests
      # -----------------------------
      - run: npm run test:unit
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}

      - run: npm run test:e2e:test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}

      # -----------------------------
      # Build NestJS
      # -----------------------------
      - run: npm run build

      # -----------------------------
      # Docker build
      # -----------------------------
      - name: Docker build
        run: docker build -t api-football .

      # -----------------------------
      # Docker Compose env
      # -----------------------------
      - name: Create .env.docker
        run: |
          echo "POSTGRES_USER=postgres" > .env.docker
          echo "POSTGRES_PASSWORD=postgres" >> .env.docker
          echo "POSTGRES_DB=club" >> .env.docker
          echo "DATABASE_URL=postgresql://postgres:postgres@db:5432/club?schema=public" >> .env.docker
          echo "JWT_SECRET=${{ secrets.JWT_SECRET_TEST }}" >> .env.docker
          echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET_TEST }}" >> .env.docker
          echo "JWT_RESET_SECRET=${{ secrets.JWT_RESET_SECRET_TEST }}" >> .env.docker
          echo "JWT_VERIFY_SECRET=${{ secrets.JWT_VERIFY_SECRET_TEST }}" >> .env.docker
          echo "MAIL_FROM=${{ secrets.MAIL_FROM_TEST }}" >> .env.docker
          echo "GMAIL_USER=${{ secrets.GMAIL_USER_TEST }}" >> .env.docker
          echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD_TEST }}" >> .env.docker
          echo "FRONTEND_URL=https://mon-frontend-docker.com" >> .env.docker
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN_TEST }}" >> .env.docker
          echo "SUPERADMIN_EMAIL=${{ secrets.SUPERADMIN_EMAIL_TEST }}" >> .env.docker
          echo "SUPERADMIN_PASSWORD=${{ secrets.SUPERADMIN_PASSWORD_TEST }}" >> .env.docker
          echo "THROTTLE_TTL=900" >> .env.docker
          echo "THROTTLE_LIMIT=100" >> .env.docker
          echo "NODE_ENV=production" >> .env.docker
          echo "PORT=3002" >> .env.docker
          echo "CLOUDINARY_CLOUD_NAME=do3nd2woi" >> .env.docker
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY_TEST }}" >> .env.docker
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET_TEST }}" >> .env.docker

      # -----------------------------
      # Run Docker Compose
      # -----------------------------
      - name: Run Docker Compose
        run: |
          docker compose --env-file .env.docker up -d --build
          docker compose ps

      # -----------------------------
      # Cleanup
      # -----------------------------
      - name: Stop containers
        if: always()
        run: docker compose --env-file .env.docker down
