name: CI - NestJS API

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: test_club
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Prisma generate
        run: npx prisma generate

      # -----------------------------
      # GÃ©nÃ©rer le fichier .env.test
      # -----------------------------
      - name: Create .env.test
        run: |
          echo "NODE_ENV=test" > .env.test
          echo "DATABASE_URL=${{ secrets.DATABASE_URL_TEST }}" >> .env.test
          echo "JWT_SECRET=${{ secrets.JWT_SECRET_TEST }}" >> .env.test
          echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET_TEST }}" >> .env.test
          echo "JWT_RESET_SECRET=${{ secrets.JWT_RESET_SECRET_TEST }}" >> .env.test
          echo "JWT_VERIFY_SECRET=${{ secrets.JWT_VERIFY_SECRET_TEST }}" >> .env.test
          echo "MAIL_FROM=${{ secrets.MAIL_FROM_TEST }}" >> .env.test
          echo "GMAIL_USER=${{ secrets.MAIL_USER_TEST }}" >> .env.test
          echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD_TEST }}" >> .env.test
          echo "FRONTEND_URL=https://mon-frontend-test.com" >> .env.test
          echo "SENTRY_DSN=https://7db3009f0acad40c98be38dcbfe325df@o4510425768460288.ingest.de.sentry.io/4510425773441104" >> .env.test
          echo "SUPERADMIN_EMAIL=${{ secrets.SUPERADMIN_EMAIL_TEST }}" >> .env.test
          echo "SUPERADMIN_PASSWORD=${{ secrets.SUPERADMIN_PASSWORD_TEST }}" >> .env.test
          echo "THROTTLE_TTL=900" >> .env.test
          echo "THROTTLE_LIMIT=100" >> .env.test
          echo "PORT=3003" >> .env.test
          echo "PROMETHEUS_PORT=9090" >> .env.test
          echo "GRAFANA_PORT=3000" >> .env.test

      - name: Reset Test DB
        run: npm run test:reset

      - name: Seed Test DB
        run: npm run seed  

      - name: Run unit tests (Jest)
        run: npm run test:unit

      - name: Run e2e tests (Supertest)
        run: npm run test:e2e:test

      - name: Build NestJS
        run: npm run build

      - name: Docker build (optional)
        run: docker build -t api-football .
